"""events table

Revision ID: 26b39252e715
Revises: b89e807c0e87
Create Date: 2019-04-24 17:37:33.938029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b39252e715'
down_revision = 'b89e807c0e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_index(op.f('ix_event_date_event'), 'event', ['date_event'], unique=False)
    op.create_index(op.f('ix_user_date'), 'user', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_date'), table_name='user')
    op.drop_index(op.f('ix_event_date_event'), table_name='event')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    # ### end Alembic commands ###
